apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-dev

resources:
  - ../base
  - ./namespace.yaml

configMapGenerator:
  - name: nginx-config
    files:
      - ./nginx.conf